// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQk2YF1QnwFkHfGpA9Zpq-JqrpnEkGfg',
    appId: '1:189089254768:web:12abe0ab2ddd18144bd3b5',
    messagingSenderId: '189089254768',
    projectId: 'apptutores-b5fac',
    authDomain: 'apptutores-b5fac.firebaseapp.com',
    storageBucket: 'apptutores-b5fac.firebasestorage.app',
    measurementId: 'G-ZFKKZL382S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT0Nae1qTpDqYePdduTeh70NfglrOnKtc',
    appId: '1:189089254768:android:a99d7151c5feb03c4bd3b5',
    messagingSenderId: '189089254768',
    projectId: 'apptutores-b5fac',
    storageBucket: 'apptutores-b5fac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX4CKwL5lHuEKLw6i8phDyRtJVcpyigjU',
    appId: '1:189089254768:ios:2a559a6ec9b5ce514bd3b5',
    messagingSenderId: '189089254768',
    projectId: 'apptutores-b5fac',
    storageBucket: 'apptutores-b5fac.firebasestorage.app',
    iosBundleId: 'com.example.tutoresApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX4CKwL5lHuEKLw6i8phDyRtJVcpyigjU',
    appId: '1:189089254768:ios:2a559a6ec9b5ce514bd3b5',
    messagingSenderId: '189089254768',
    projectId: 'apptutores-b5fac',
    storageBucket: 'apptutores-b5fac.firebasestorage.app',
    iosBundleId: 'com.example.tutoresApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdQk2YF1QnwFkHfGpA9Zpq-JqrpnEkGfg',
    appId: '1:189089254768:web:4f0f107fb9b90eb04bd3b5',
    messagingSenderId: '189089254768',
    projectId: 'apptutores-b5fac',
    authDomain: 'apptutores-b5fac.firebaseapp.com',
    storageBucket: 'apptutores-b5fac.firebasestorage.app',
    measurementId: 'G-8SLYBV1HZL',
  );
}
